import type { Team, Player, AuctionSettings } from "./types"

export const defaultSettings: AuctionSettings = {
  initialBudget: 180,
  minSquadSize: 11,
  maxSquadSize: 15,
  currentPhase: "Team Auction",
}

// Available franchises for bidding
export const availableFranchises = [
  { "id": "f1", "name": "Mumbai Indians", "logo": "mumbai-indians-logo.jpg" },
  { "id": "f2", "name": "Chennai Super Kings", "logo": "chennai-super-kings-logo.jpg" },
  { "id": "f3", "name": "Royal Challengers Bangalore", "logo": "royal-challengers-bangalore-logo.jpg" },
  { "id": "f4", "name": "Delhi Capitals", "logo": "delhi-capitals-logo.jpg" },
  { "id": "f5", "name": "Kolkata Knight Riders", "logo": "kolkata-knight-riders-logo.jpg" },
  { "id": "f6", "name": "Punjab Kings", "logo": "punjab-kings-logo.jpg" },
  { "id": "f7", "name": "Sunrisers Hyderabad", "logo": "sunrisers-hyderabad-logo.jpg" },
  { "id": "f8", "name": "Rajasthan Royals", "logo": "rajasthan-royals-logo.jpg" },
  { "id": "f9", "name": "Gujarat Titans", "logo": "gujarat-titans-logo.jpg" },
  { "id": "f10", "name": "Lucknow Super Giants", "logo": "lucknow-super-giants-logo.jpg" }
]

export const mockTeams: Team[] = [
  {
    id: "t1",
    groupName: "Group Alpha",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-blue.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t2",
    groupName: "Group Beta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-yellow.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t3",
    groupName: "Group Gamma",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-red.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t4",
    groupName: "Group Delta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-navy.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t5",
    groupName: "Group Epsilon",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-purple.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t6",
    groupName: "Group Zeta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-orange.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t7",
    groupName: "Group Eta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-black.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t8",
    groupName: "Group Theta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-pink.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t9",
    groupName: "Group Iota",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-green.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t10",
    groupName: "Group Kappa",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: defaultSettings.initialBudget,
    logo: "/cricket-team-logo-teal.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  }
]

export const mockPlayers: Player[] = [
    {
        "id": "p110",
        "name": "Abdul Samad",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p223",
        "name": "Abhinandan Singh",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p240",
        "name": "Abhishek Sharma",
        "role": "All-rounder",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p33",
        "name": "Abishek Porel",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p197",
        "name": "Adam Milne",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "New Zealand",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p102",
        "name": "Aiden Markram",
        "role": "Batsman",
        "basePrice": 1.5,
        "country": "South Africa",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p39",
        "name": "Ajay Mandal",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p76",
        "name": "Ajinkya Rahane",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p96",
        "name": "Akash Deep",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p119",
        "name": "Akash Singh",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p23",
        "name": "Akeal Hosein",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "West Indies",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p106",
        "name": "Akshat Raghuwanshi",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p149",
        "name": "Allah Gazanfar",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "Afghanistan",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p14",
        "name": "Aman Khan",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p181",
        "name": "Aman Rao Perala",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p248",
        "name": "Amit Kumar",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p78",
        "name": "Angkrish Raghuvanshii",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p227",
        "name": "Aniket Verma",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p122",
        "name": "Anrich Nortje",
        "role": "Bowler",
        "basePrice": 1.5,
        "country": "South Africa",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p9",
        "name": "Anshul Kamboj",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p54",
        "name": "Anuj Rawat",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p86",
        "name": "Anukul Roy",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p42",
        "name": "Aquib Dar",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p121",
        "name": "Arjun Tendulkar",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p168",
        "name": "Arshdeep Singh (Star Player)",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p112",
        "name": "Arshin Kulkarni",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p71",
        "name": "Ashok Sharma",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p37",
        "name": "Ashutosh Sharma",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p146",
        "name": "Ashwani Kumar",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p138",
        "name": "Atharva Ankolekar",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p116",
        "name": "Avesh Khan",
        "role": "Bowler",
        "basePrice": 1.5,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p35",
        "name": "Axar Patel",
        "role": "All-rounder",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p114",
        "name": "Ayush Badoni",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p5",
        "name": "Ayush Mhatre",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p161",
        "name": "Azmatullah Omarzai",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "Afghanistan",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p29",
        "name": "Ben Duckett",
        "role": "Wk/Batsman",
        "basePrice": 1.0,
        "country": "England",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p167",
        "name": "Ben Dwarshuis",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "Australia",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p221",
        "name": "Bhuvneshwar Kumar",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p196",
        "name": "Brijesh Sharma",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p235",
        "name": "Brydon Carse",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "England",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p80",
        "name": "Cameron Green",
        "role": "All-rounder",
        "basePrice": 2.0,
        "country": "Australia",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p166",
        "name": "Cooper Connolly",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "Australia",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p140",
        "name": "Corbin Bosch",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "South Africa",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p88",
        "name": "Daksh Kamra",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p132",
        "name": "Danish Malewar",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p28",
        "name": "David Miller",
        "role": "Batsman",
        "basePrice": 1.5,
        "country": "South Africa",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p145",
        "name": "Deepak Chahar",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p202",
        "name": "Devdutt Padikkal",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p4",
        "name": "Dewald Brevis",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "South Africa",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p184",
        "name": "Dhruv Jurel",
        "role": "Wk/Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p118",
        "name": "Digvesh Singh",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p178",
        "name": "Donovan Ferriria",
        "role": "Wk/Batsman",
        "basePrice": 1.0,
        "country": "South Africa",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p47",
        "name": "Dushmantha Chameera",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "Sri Lanka",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p245",
        "name": "Eshan Malinga",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "Sri Lanka",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p81",
        "name": "Finn Allen",
        "role": "Wk/Batsman",
        "basePrice": 0.5,
        "country": "New Zealand",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p56",
        "name": "Glenn Phillips",
        "role": "Batsman",
        "basePrice": 1.5,
        "country": "New Zealand",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p22",
        "name": "Gurjapneet Singh",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p69",
        "name": "Gurnoor Singh Brar",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p134",
        "name": "Hardik Pandya(Star Player)",
        "role": "All-rounder",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p154",
        "name": "Harnoor Pannu",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p159",
        "name": "Harpreet Brar",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p234",
        "name": "Harsh Dubey",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p232",
        "name": "Harshal Patel",
        "role": "All-rounder",
        "basePrice": 1.5,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p97",
        "name": "Harshit Rana",
        "role": "Bowler",
        "basePrice": 1.5,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p230",
        "name": "Heinrich Klassen",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "South Africa",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p103",
        "name": "Himmat Singh",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p226",
        "name": "Ishan Kishan",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p70",
        "name": "Ishant Sharma",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p239",
        "name": "Jack Edwards",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "Australia",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p211",
        "name": "Jacob Bethell",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "England",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p224",
        "name": "Jacob Duffy",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "New Zealand",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p10",
        "name": "Jamie Overton",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "England",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p62",
        "name": "Jason Holder",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "West Indies",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p150",
        "name": "Jasprit Bumrah (Star Player)",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p61",
        "name": "Jayant Yadav",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p244",
        "name": "Jaydev Unadkat",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p205",
        "name": "Jitesh Sharma",
        "role": "Wk/Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p189",
        "name": "Jofra Archer",
        "role": "Bowler",
        "basePrice": 1.5,
        "country": "England",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p206",
        "name": "Jordan Cox",
        "role": "Wk/Batsman",
        "basePrice": 0.5,
        "country": "England",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p52",
        "name": "Jos Buttler",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "England",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p218",
        "name": "Josh Hazlewood",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "Australia",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p107",
        "name": "Josh Inglis",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "Australia",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p26",
        "name": "KL Rahul",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p65",
        "name": "Kagiso Rabada",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "South Africa",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p233",
        "name": "Kamindu Mendis",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "Sri Lanka",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p217",
        "name": "Kanishk Chouhan",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p6",
        "name": "Kartik Sharma",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p93",
        "name": "Kartik Tyagi",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p27",
        "name": "Karun Nair",
        "role": "Batsman",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p17",
        "name": "Khaleel Ahmed",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p237",
        "name": "Krains Fuletra",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "india",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p207",
        "name": "Krunal Pandya",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p198",
        "name": "Kuldeep Sen",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p50",
        "name": "Kuldeep Yadav",
        "role": "Bowler",
        "basePrice": 1.5,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p53",
        "name": "Kumar Kushagra",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p191",
        "name": "Kwena Maphaka",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "South Africa",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p49",
        "name": "Kyle Jamieson",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "New Zealand",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p179",
        "name": "Lhuan-dre Pretorius",
        "role": "Batsman",
        "basePrice": 0.5,
        "country": "South Africa",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p238",
        "name": "Liam Livingstone",
        "role": "All-rounder",
        "basePrice": 1.5,
        "country": "England",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p175",
        "name": "Lockie Ferguson",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "New Zealand",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p73",
        "name": "Luke Wood",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "England",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p48",
        "name": "Lungi Ngidi",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "South Africa",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p117",
        "name": "M Siddharth",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p1",
        "name": "MS Dhoni",
        "role": "Wk/Batsman",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p41",
        "name": "Madhav Tiwari",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p68",
        "name": "Manav Suthar",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p214",
        "name": "Mangesh Yadav",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p79",
        "name": "Manish Pandey",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p160",
        "name": "Marco Jansen",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "South Africa",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p158",
        "name": "Marcus Stoinis",
        "role": "All-rounder",
        "basePrice": 2.0,
        "country": "Australia",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p92",
        "name": "Matheesha Pathirana",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "Sri Lanka",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p13",
        "name": "Mathew Willam Short",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "Australia",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p24",
        "name": "Matt Henry",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "New Zealand",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p104",
        "name": "Matthew Breetzke",
        "role": "Batsman",
        "basePrice": 0.5,
        "country": "South Africa",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p144",
        "name": "Mayank Markande",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p139",
        "name": "Mayank Rawat",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p124",
        "name": "Mayank Yadav",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p165",
        "name": "Mitch Owen",
        "role": "Wk/Batsman",
        "basePrice": 0.5,
        "country": "Australia",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p109",
        "name": "Mitchell Marsh",
        "role": "All-rounder",
        "basePrice": 2.0,
        "country": "Australia",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p136",
        "name": "Mitchell Santner",
        "role": "All-rounder",
        "basePrice": 1.5,
        "country": "New Zealand",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p44",
        "name": "Mitchell Starc (Star Player)",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "Australia",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p148",
        "name": "Mohammad Izhar",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p115",
        "name": "Mohammed Shami",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p66",
        "name": "Mohammed Siraj",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p59",
        "name": "Mohd. Arshad Khan",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p125",
        "name": "Mohsin Khan",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p19",
        "name": "Mukesh Choudhary",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p46",
        "name": "Mukesh Kumar",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p105",
        "name": "Mukul Choudhary",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p163",
        "name": "Musheer Khan",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p95",
        "name": "Mustafizur Rahman",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "Bangladesh",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p135",
        "name": "Naman Dhir",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p123",
        "name": "Naman Tiwari",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p200",
        "name": "Nandre Burger",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "South Africa",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p20",
        "name": "Nathan Ellis",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "Australia",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p152",
        "name": "Nehal Wadhera",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p108",
        "name": "Nicholas Pooran",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "West Indies",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p57",
        "name": "Nishant Sindhu",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p241",
        "name": "Nitish Kumar Reddy",
        "role": "All-rounder",
        "basePrice": 1.5,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p43",
        "name": "Nitish Rana",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p18",
        "name": "Noor Ahmed",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "Afghanistan",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p222",
        "name": "Nuwan Thushara",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "Sri Lanka",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p247",
        "name": "Onkar Tarmale",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p242",
        "name": "Pat Cummins",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "Australia",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p30",
        "name": "Pathum Nissanka",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "Sri Lanka",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p204",
        "name": "Phil Salt",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "England",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p156",
        "name": "Prabhsimran Singh",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p249",
        "name": "Praful Hinge",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p94",
        "name": "Prashant Solanki",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p12",
        "name": "Prashant Veer",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p67",
        "name": "Prasidh Krishna",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p173",
        "name": "Pravin Dubey",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p120",
        "name": "Prince Yadav",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p72",
        "name": "Prithvi Raj Yarra",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p32",
        "name": "Prithvi Shaw",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p162",
        "name": "Priyansh Arya",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p155",
        "name": "Pyla Avinash",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p131",
        "name": "Quinton De Kock",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "South Africa",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p60",
        "name": "R Sai Kishore",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p89",
        "name": "Rachin Ravindra",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "New Zealand",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p147",
        "name": "Raghu Sharma",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p25",
        "name": "Rahul Chahar",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p74",
        "name": "Rahul Tewatia",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p83",
        "name": "Rahul Tripathi",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p137",
        "name": "Raj Angad Bawa",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p201",
        "name": "Rajat Patidar",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p11",
        "name": "Ramakrishna Gosh",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p90",
        "name": "Ramandeep Singh",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p75",
        "name": "Rashid Khan",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "Afghanistan",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p219",
        "name": "Rasikh Dar",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p192",
        "name": "Ravi Bishnoi",
        "role": "Bowler",
        "basePrice": 1.5,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p180",
        "name": "Ravi Singh",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p187",
        "name": "Ravindra Jadeja",
        "role": "All-rounder",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p77",
        "name": "Rinku Singh",
        "role": "Batsman",
        "basePrice": 1.5,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p101",
        "name": "Rishabh Pant",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p185",
        "name": "Riyan Parag",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p128",
        "name": "Robin Minz",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p126",
        "name": "Rohit Sharma",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p210",
        "name": "Romario Shepherd",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "West Indies",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p85",
        "name": "Rovman Powel",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "West Indies",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p3",
        "name": "Ruturaj Gaikwad",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p130",
        "name": "Ryan Rickelton",
        "role": "Wk/Batsman",
        "basePrice": 0.5,
        "country": "South Africa",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p31",
        "name": "Sahil Parakh",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p63",
        "name": "Sai Sudharsan",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p246",
        "name": "Sakib Hussain",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p229",
        "name": "Salil Arora",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p188",
        "name": "Sam Curran",
        "role": "All-rounder",
        "basePrice": 2.0,
        "country": "England",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p36",
        "name": "Sameer Rizvi",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p199",
        "name": "Sandeep Sharma",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p2",
        "name": "Sanju Samson",
        "role": "Wk/Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p7",
        "name": "Sarfaraz Khan",
        "role": "Batsman",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p87",
        "name": "Sarthak Ranjan",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p213",
        "name": "Satvik Deswal",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p111",
        "name": "Shahbaz Ahamad",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p64",
        "name": "Shahrukh Khan",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p142",
        "name": "Shardul Thakur",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p157",
        "name": "Shashank Singh",
        "role": "Batsman",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p129",
        "name": "Sherfane Rutherford",
        "role": "Batsman",
        "basePrice": 0.5,
        "country": "West Indies",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p182",
        "name": "Shimron Hetmyer",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "West Indies",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p16",
        "name": "Shivam Dube",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p250",
        "name": "Shivam Mavi",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p236",
        "name": "Shivang Kumar",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p21",
        "name": "Shreyas Gopal",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p151",
        "name": "Shreyas Iyer(Star Player)",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p176",
        "name": "Shubham Dubey",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p51",
        "name": "Shubman Gill",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p228",
        "name": "Smaran Ravichandran",
        "role": "Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p99",
        "name": "Sunil Narine",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "West Indies",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p127",
        "name": "Suryakumar Yadav (Star Player)",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p164",
        "name": "Suryansh Shedge",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p193",
        "name": "Sushant Mishra",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p220",
        "name": "Suyash Sharma",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p208",
        "name": "Swapnil Singh",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        // "isStarPlayer": false
    },
    {
        "id": "p45",
        "name": "T Natarajan",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p82",
        "name": "Tejasvi Singh",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p133",
        "name": "Tilak Varma",
        "role": "Batsman",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p209",
        "name": "Tim David",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "Australia",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p84",
        "name": "Tim Seifert",
        "role": "Wk/Batsman",
        "basePrice": 0.5,
        "country": "New Zealand",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p55",
        "name": "Tom Banton",
        "role": "Wk/Batsman",
        "basePrice": 0.5,
        "country": "England",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p231",
        "name": "Travis Head",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "Australia",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p143",
        "name": "Trent Boult",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "New Zealand",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p40",
        "name": "Tripurana Vijay",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p34",
        "name": "Tristan Stubbs",
        "role": "Wk/Batsman",
        "basePrice": 0.5,
        "country": "South Africa",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p190",
        "name": "Tushar Deshpande",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p98",
        "name": "Umran Malik",
        "role": "Bowler",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p8",
        "name": "Urvil Patel",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p91",
        "name": "Vaibhav Arora",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p177",
        "name": "Vaibhav Suryavanshi",
        "role": "Batsman",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p100",
        "name": "Varun Chakravarthy",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "KKR",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p212",
        "name": "Venkatesh Iyer",
        "role": "All-rounder",
        "basePrice": 1.0,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p215",
        "name": "Vicky Ostwal",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p195",
        "name": "Vignesh Puthur",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p216",
        "name": "Vihaan Malhotra",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p38",
        "name": "Vipraj Nigam",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Delhi Capitals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p203",
        "name": "Virat Kohli",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p174",
        "name": "Vishal Nishad",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p153",
        "name": "Vishnu Vinod",
        "role": "Wk/Batsman",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p170",
        "name": "Vyshak Vijay Kumar",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p113",
        "name": "Wanindu Hasaranga",
        "role": "All-rounder",
        "basePrice": 1.5,
        "country": "Sri Lanka",
        "originalTeam": "Lucknow Super Giants",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p58",
        "name": "Washington Sundar",
        "role": "All-rounder",
        "basePrice": 1.5,
        "country": "India",
        "originalTeam": "Gujarat Titans",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p141",
        "name": "Will Jacks",
        "role": "Batsman",
        "basePrice": 1.0,
        "country": "England",
        "originalTeam": "Mumbai Indians",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p172",
        "name": "Xavier Bartlett",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "Australia",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p225",
        "name": "Yash Dayal",
        "role": "Bowler",
        "basePrice": 0.5,
        "country": "India",
        "originalTeam": "RCB",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p194",
        "name": "Yash Raj Punja",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p171",
        "name": "Yash Thakur",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p183",
        "name": "Yashasvi Jaiswal",
        "role": "Batsman",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": true
    },
    {
        "id": "p186",
        "name": "Yudhvir Singh",
        "role": "All-rounder",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Rajasthan Royals",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p169",
        "name": "Yuzi Chahal",
        "role": "Bowler",
        "basePrice": 2.0,
        "country": "India",
        "originalTeam": "Punjab Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p15",
        "name": "Zak Foulkes",
        "role": "All-rounder",
        "basePrice": 0.5,
        "country": "New Zealand",
        "originalTeam": "Chennai Super Kings",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    },
    {
        "id": "p243",
        "name": "Zeeshan Ansari",
        "role": "Bowler",
        "basePrice": 0.2,
        "country": "India",
        "originalTeam": "Sunrisers Hyderabad",
        "currentTeam": null,
        "purchasePrice": null,
        "status": "Unsold",
        "isStarPlayer": false
    }
]