import type { Team, Player, AuctionSettings } from "./types"

// Helper function to generate random ratings
const generateRatings = (overallRating: number) => ({
  overall: overallRating,
  powerplayBatting: Math.floor(Math.random() * 11),
  powerplayBowling: Math.floor(Math.random() * 11),
  middleOversBatting: Math.floor(Math.random() * 11),
  middleOversBowling: Math.floor(Math.random() * 11),
  deathOversBatting: Math.floor(Math.random() * 11),
  deathOversBowling: Math.floor(Math.random() * 11),
})

export const defaultSettings: AuctionSettings = {
  initialBudget: 100,
  minSquadSize: 11,
  maxSquadSize: 15,
  currentPhase: "Team Auction",
}

// Available franchises for bidding
export const availableFranchises = [
  { id: "f1", name: "Mumbai Warriors", logo: "/cricket-team-logo-blue.jpg" },
  { id: "f2", name: "Chennai Kings", logo: "/cricket-team-logo-yellow.jpg" },
  { id: "f3", name: "Bangalore Royals", logo: "/cricket-team-logo-red.jpg" },
  { id: "f4", name: "Delhi Capitals", logo: "/cricket-team-logo-navy.jpg" },
  { id: "f5", name: "Kolkata Riders", logo: "/cricket-team-logo-purple.jpg" },
  { id: "f6", name: "Punjab Strikers", logo: "/cricket-team-logo-orange.jpg" },
  { id: "f7", name: "Hyderabad Titans", logo: "/cricket-team-logo-black.jpg" },
  { id: "f8", name: "Rajasthan Challengers", logo: "/cricket-team-logo-pink.jpg" },
]

export const mockTeams: Team[] = [
  {
    id: "t1",
    groupName: "Group Alpha",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: 100,
    logo: "/cricket-team-logo-blue.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t2",
    groupName: "Group Beta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: 100,
    logo: "/cricket-team-logo-yellow.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t3",
    groupName: "Group Gamma",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: 100,
    logo: "/cricket-team-logo-red.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t4",
    groupName: "Group Delta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: 100,
    logo: "/cricket-team-logo-navy.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t5",
    groupName: "Group Epsilon",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: 100,
    logo: "/cricket-team-logo-purple.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t6",
    groupName: "Group Zeta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: 100,
    logo: "/cricket-team-logo-orange.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t7",
    groupName: "Group Eta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: 100,
    logo: "/cricket-team-logo-black.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
  {
    id: "t8",
    groupName: "Group Theta",
    franchiseName: null,
    franchiseBid: 0,
    remainingBudget: 100,
    logo: "/cricket-team-logo-pink.jpg",
    squadPlayerIds: [],
    rtmUsed: false,
    rtsUsed: false,
    teamAuctionComplete: false,
  },
]

export const mockPlayers: Player[] = [
  // Star Batsmen (High ratings)
  {
    id: "p1",
    name: "Virat Sharma",
    role: "Batsman",
    basePrice: 2.0,
    country: "India",
    ratings: generateRatings(92),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
    isStarPlayer: true,
  },
  {
    id: "p2",
    name: "Rohit Patel",
    role: "Batsman",
    basePrice: 2.0,
    country: "India",
    ratings: generateRatings(90),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
    isStarPlayer: true,
  },
  {
    id: "p3",
    name: "Kane Williamson",
    role: "Batsman",
    basePrice: 1.5,
    country: "New Zealand",
    ratings: generateRatings(88),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p4",
    name: "David Warner",
    role: "Batsman",
    basePrice: 1.5,
    country: "Australia",
    ratings: generateRatings(89),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p5",
    name: "Shubman Kumar",
    role: "Batsman",
    basePrice: 1.0,
    country: "India",
    ratings: generateRatings(85),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p6",
    name: "KL Singh",
    role: "Batsman",
    basePrice: 1.0,
    country: "India",
    ratings: generateRatings(84),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p7",
    name: "Jos Buttler",
    role: "Batsman",
    basePrice: 1.5,
    country: "England",
    ratings: generateRatings(86),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p8",
    name: "Quinton de Kock",
    role: "Batsman",
    basePrice: 1.0,
    country: "South Africa",
    ratings: generateRatings(83),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },

  // Star Bowlers
  {
    id: "p9",
    name: "Jasprit Yadav",
    role: "Bowler",
    basePrice: 2.0,
    country: "India",
    ratings: generateRatings(93),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
    isStarPlayer: true,
  },
  {
    id: "p10",
    name: "Mitchell Starc",
    role: "Bowler",
    basePrice: 2.0,
    country: "Australia",
    ratings: generateRatings(91),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
    isStarPlayer: true,
  },
  {
    id: "p11",
    name: "Kagiso Rabada",
    role: "Bowler",
    basePrice: 1.5,
    country: "South Africa",
    ratings: generateRatings(89),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p12",
    name: "Rashid Khan",
    role: "Bowler",
    basePrice: 1.5,
    country: "Afghanistan",
    ratings: generateRatings(90),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p13",
    name: "Trent Boult",
    role: "Bowler",
    basePrice: 1.0,
    country: "New Zealand",
    ratings: generateRatings(87),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p14",
    name: "Pat Cummins",
    role: "Bowler",
    basePrice: 1.5,
    country: "Australia",
    ratings: generateRatings(88),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },

  // Star All-Rounders
  {
    id: "p15",
    name: "Ben Stokes",
    role: "All-rounder",
    basePrice: 2.0,
    country: "England",
    ratings: generateRatings(94),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
    isStarPlayer: true,
  },
  {
    id: "p16",
    name: "Hardik Reddy",
    role: "All-rounder",
    basePrice: 2.0,
    country: "India",
    ratings: generateRatings(91),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
    isStarPlayer: true,
  },
  {
    id: "p17",
    name: "Andre Russell",
    role: "All-rounder",
    basePrice: 1.5,
    country: "West Indies",
    ratings: generateRatings(89),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p18",
    name: "Glenn Maxwell",
    role: "All-rounder",
    basePrice: 1.5,
    country: "Australia",
    ratings: generateRatings(87),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p19",
    name: "Ravindra Pandey",
    role: "All-rounder",
    basePrice: 1.0,
    country: "India",
    ratings: generateRatings(86),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },
  {
    id: "p20",
    name: "Sam Curran",
    role: "All-rounder",
    basePrice: 1.0,
    country: "England",
    ratings: generateRatings(84),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold",
  },

  // Additional Batsmen
  ...Array.from({ length: 60 }, (_, i) => ({
    id: `p${21 + i}`,
    name: `Batsman ${i + 1}`,
    role: "Batsman" as const,
    basePrice: 0.2 + Math.floor(Math.random() * 8) * 0.1,
    country: i % 2 === 0 ? "India" : ["Australia", "England", "South Africa", "New Zealand"][i % 4],
    ratings: generateRatings(Math.floor(Math.random() * 30) + 60),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold" as const,
  })),

  // Additional Bowlers
  ...Array.from({ length: 60 }, (_, i) => ({
    id: `p${81 + i}`,
    name: `Bowler ${i + 1}`,
    role: "Bowler" as const,
    basePrice: 0.2 + Math.floor(Math.random() * 8) * 0.1,
    country: i % 2 === 0 ? "India" : ["Australia", "England", "West Indies", "Pakistan"][i % 4],
    ratings: generateRatings(Math.floor(Math.random() * 30) + 60),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold" as const,
  })),

  // Additional All-Rounders
  ...Array.from({ length: 70 }, (_, i) => ({
    id: `p${141 + i}`,
    name: `All-rounder ${i + 1}`,
    role: "All-rounder" as const,
    basePrice: 0.2 + Math.floor(Math.random() * 8) * 0.1,
    country: i % 2 === 0 ? "India" : ["Australia", "England", "Sri Lanka", "Bangladesh"][i % 4],
    ratings: generateRatings(Math.floor(Math.random() * 30) + 60),
    originalTeam: null,
    currentTeam: null,
    purchasePrice: null,
    status: "Unsold" as const,
  })),
]
